services:
  web:
    image: ubuntu/nginx
    container_name: nginx_server 
    ports:
      - "8086:80" # mapeo de puertos  HTTP
      - "443:443" # mapeo de puertos HTTPS
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # archivo de configuraci칩n principal
      - ./sites-available:/etc/nginx/sites-available # archivos de configuraci칩n de hosts virtuales
      - ./websites:/var/www/html/ # directorio de los sitios web
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd # archivo de contrase침as
      - ./certs/:/etc/nginx/certs # certificados
      - ./scripts:/docker-entrypoint.d/ # directorio de scripts
    restart: always # reinicio autom치tico